apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30004
      name: nginx-port
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30005
      name: vite-dev-port
  type: NodePort
