apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-backend
  labels:
    app: nginx-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-backend
  template:
    metadata:
      labels:
        app: nginx-backend
    spec:
      containers:
        - name: nginx-backend
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-backend
              mountPath: /etc/nginx/conf.d
            - name: nginx-logs
              mountPath: /var/log/nginx
      volumes:
        - name: nginx-config-backend
          configMap:
            name: nginx-config-backend
        - name: nginx-logs
          persistentVolumeClaim:
            claimName: nginx-log-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-log-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi


