version: '3.8'

services:
  web:
    build:
      context: ./unicorn-frontend
      dockerfile: Dockerfile
      target: ${TARGET:-prod}
    ports:
      - 5050:5173  # Vite Dev server (frontend)
      - 3000:80    # Production Nginx (serves frontend)
    volumes:
      - ./unicorn-frontend:/app/web
    depends_on:
      - api
    restart: on-failure:10
    healthcheck:
      test: curl --fail http://localhost:5050 || exit 1  # Frontend healthcheck
      start_period: 5s
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - full_stack

  api:
    build:
      context: ./unicorn-backend
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - 8888:80  # Expose Nginx proxy on port 8080
      - 8000:8000  # Laravel API on 8000
    volumes:
      - ./unicorn-backend:/app/api
    environment:
      APP_ENV: local
      APP_DEBUG: 1
      APP_KEY: base64:$(head -c 32 /dev/urandom | base64)
    restart: on-failure:10
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1  # API healthcheck
      start_period: 10s
      interval: 30s
      timeout: 5s
      retries: 3
    command: ["/bin/sh", "-c", "php artisan migrate:refresh --seed && php-fpm -D && nginx -g 'daemon off;'"]  
    networks:
      - full_stack

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment: 
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./unicorn-backend/mysql:/var/lib/mysql # Persist MySQL data
    networks:
      - full_stack 

networks:
  full_stack: {}
