# Stage 1: Build
FROM node:23-alpine3.19 AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json for dependency installation
COPY ./unicorn-frontend/package.json ./unicorn-frontend/package-lock.json ./

# Install dependencies
RUN npm install

# Copy the application source
COPY ./unicorn-frontend ./

# Build the application
RUN npm run build

# Stage 2: Runtime
FROM node:23-alpine3.19 AS runtime

# Set working directory
WORKDIR /app

# Copy built application from the builder stage
COPY --from=builder /app/dist /app/dist

# Expose port 3000
EXPOSE 3000

# Default command to serve the application using http-server
CMD ["npx", "http-server", "dist", "-p", "3000"]
