# Stage 1: Build
FROM node:23-alpine3.19 AS builder

# Set working directory
WORKDIR /app

# Install dependencies
COPY ./unicorn-frontend/package.json ./unicorn-frontend/package-lock.json ./
RUN npm install

# Copy the application source
COPY . .

# Build the application
RUN npm run build

# Stage 2: Runtime
FROM node:23-alpine3.19 AS runtime

# Set working directory
WORKDIR /app

# Copy built application from builder
COPY --from=builder /app/dist /app/dist

# Expose port
EXPOSE 8080

# Default command to serve the app
CMD ["npx", "http-server", "dist", "-p", "8080"]
