FROM node:23-alpine3.19 AS base
WORKDIR /app/web

COPY ./unicorn-frontend/package.json ./unicorn-frontend/package-lock.json ./

# Perform a clean npm install
RUN npm cache clean --force && npm install

COPY ./unicorn-frontend .

### Development Stage
FROM base AS dev
EXPOSE 5173
CMD ["npm", "run", "dev"]

### Build Stage
FROM base AS build
RUN npm run build

### Production Stage with Nginx
FROM nginx:stable-alpine AS prod
COPY --from=build /app/web/dist /usr/share/nginx/html
COPY ./nginx/frontend_nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
