# Stage 1: Build dependencies using Composer
FROM composer:2 AS composer-build

WORKDIR /app

# Copy composer files
COPY ./unicorn-backend/composer.json ./unicorn-backend/composer.lock ./

# Install dependencies
RUN composer install --no-dev --optimize-autoloader --no-scripts

# Stage 2: Base image for PHP and dependencies
FROM php:8-fpm-alpine

# Set default user and UID if not provided during build
ARG user=laravel
ARG group=laravel
ARG uid=1000

# Install system dependencies and PHP extensions
RUN apk update && apk add --no-cache \
    mysql-client \
    nginx \
    bash \
    libpng-dev \
    libjpeg-turbo-dev \
    freetype-dev \
    oniguruma-dev \
    libxml2-dev \
    curl \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd pdo pdo_mysql mbstring exif pcntl bcmath opcache

# Install Composer globally
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Create developer user and group
RUN addgroup -g $uid $user && \
    adduser -u $uid -G $user -D $group -D -h /home/$user $user && \
    mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user 

# Set working directory
WORKDIR /app/api

# Copy application code
COPY ./unicorn-backend ./
# Copy composer files
COPY ./unicorn-backend/composer.json ./unicorn-backend/composer.lock ./

# Copy dependencies from the Composer build stage
COPY --from=composer-build /app/vendor ./vendor

# Set ownership of application directory
RUN chown -R $user:$user /app/api

# Copy Nginx configuration
COPY ./nginx/backend_nginx.conf /etc/nginx/nginx.conf

# Expose Nginx (80) and PHP-FPM (9000) ports
EXPOSE 80 9000

# Default command to run the application
#CMD ["sh", "-c", "composer install && php artisan migrate:refresh --seed && php-fpm -D && nginx -g 'daemon off;'"]
CMD ["sh", "-c", "composer install && php-fpm -D && nginx -g 'daemon off;'"]

#CMD ["sh", "-c", "if [ ! -f /app/api/composer.json ]; then echo 'Missing application files'; exit 1; fi; php artisan migrate:refresh --seed && php-fpm -D && nginx -g 'daemon off;'"]

