apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-env-config
data:
  .env: |
    APP_NAME=Laravel
    APP_ENV=local
    APP_KEY=base64:K67B1vYpdsxaFarl36RciYKcknOEUQzFMGYLRbT0EFg=
    APP_DEBUG=true
    APP_TIMEZONE=UTC
    APP_URL=http://160.191.163.33:3000
    APP_LOCALE=en
    APP_FALLBACK_LOCALE=en
    APP_FAKER_LOCALE=en_US
    APP_MAINTENANCE_DRIVER=file
    PHP_CLI_SERVER_WORKERS=4
    BCRYPT_ROUNDS=12
    LOG_CHANNEL=stack
    LOG_STACK=single
    LOG_DEPRECATIONS_CHANNEL=null
    LOG_LEVEL=debug
    SESSION_DRIVER=database
    SESSION_LIFETIME=120
    SESSION_ENCRYPT=false
    SESSION_PATH=/
    SESSION_DOMAIN=null
    BROADCAST_CONNECTION=log
    FILESYSTEM_DISK=local
    QUEUE_CONNECTION=database
    CACHE_STORE=database
    CACHE_PREFIX=
    MEMCACHED_HOST=127.0.0.1
    MAIL_MAILER=log
    MAIL_HOST=127.0.0.1
    MAIL_PORT=2525
    MAIL_USERNAME=null
    MAIL_PASSWORD=null
    MAIL_ENCRYPTION=null
    MAIL_FROM_ADDRESS="hello@example.com"
    MAIL_FROM_NAME="${APP_NAME}"
