apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: syedkamruzzaman/unicorn_backend_image
          ports:
            - containerPort: 8888  # Expose Laravel API
          envFrom:
            - configMapRef:
                name: backend-env-config
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "secret"
            - name: MYSQL_DATABASE
              value: "laravel"
            - name: MYSQL_USER
              value: "laravel"
            - name: MYSQL_PASSWORD
              value: "secret"      
          volumeMounts:
            - name: backend-volume
              mountPath: /app/api
      volumes:
        - name: backend-volume
          emptyDir: {}
